const data = [
  {
    id: 1,
    image: 'https://source.unsplash.com/gVG8cRjHF-8',
    title: 'Meta Trap House',
    owner: '@freezecol',
    hashcode: '35897gzisoh357IOU5386EIGH99',
    category: 'ingenesis',
  },
  {
    id: 2,
    image: 'https://source.unsplash.com/c7xBEFBJhkg',
    title: 'Vincent Van Gogh',
    owner: '@vincent',
    hashcode: '35897gzisoh357IOU5386EIGH99',
    category: 'intemple',
  },
  {
    id: 3,
    image: 'https://source.unsplash.com/9sbO_vzyG40',
    title: 'Teufzer',
    owner: '@teufzer',
    hashcode: '35897gzisoh357IOU5386EIGH99',
    category: 'invoid',
  },
  {
    id: 4,
    image: 'https://source.unsplash.com/k1bO_VTiZSs',
    title: '6529 AB + 1',
    owner: '@6529',
    hashcode: '35897gzisoh357IOU5386EIGH99',
    category: 'ingenesis',
  },
  {
    id: 5,
    image: 'https://source.unsplash.com/uYyPRFmy87k',
    title: '9049',
    owner: '@rsgaya',
    hashcode: '35897gzisoh357IOU5386EIGH99',
    category: 'intemple',
  },
  {
    id: 6,
    image: 'https://source.unsplash.com/gVG8cRjHF-8',
    title: '6529 Photo A',
    owner: 'mintface',
    hashcode: '35897gzisoh357IOU5386EIGH99',
    category: '24htrending',
  },
  {
    id: 7,
    image: 'https://source.unsplash.com/70eJ0cD5ORs',
    title: 'Bored Yacht Ape',
    owner: '@boredape',
    hashcode: '35897gzisoh357IOU5386EIGH99',
    category: 'mostpopular',
  },
  {
    id: 8,
    image: 'https://source.unsplash.com/Kd2MCCeEhrc',
    title: 'Potrays',
    owner: '@potrays',
    hashcode: '35897gzisoh357IOU5386EIGH99',
    category: 'mostpopular',
  },
  {
    id: 9,
    image: 'https://source.unsplash.com/dJ4JgX5I5y8',
    title: 'Minters',
    owner: '@burnmints',
    hashcode: '35897gzisoh357IOU5386EIGH99',
    category: 'invoid',
  },
]

export default data
